# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1If8yPj30cYZHPMDHTkbACabbrWrv2MAn
"""

import numpy as np

header = [('Name', 'S100'), ('Age', int), ('Pais', 'S100')]
data = [('Andres', 14, 'Rusia'), 
        ('Amilcar', 40, 'China'), 
        ('Valeria', 16, 'Francia'), 
        ('Maria', 38, 'Estados Unidos'),
        ('Pedro', 8, 'Dubai')]

people = np.array(data, dtype=header)

np.sort(people, order='Name')